// <auto-generated />
using System;
using HatForge.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HatForge.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HatForge.Domain.Entities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToLeadId")
                        .HasColumnType("integer");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompletedQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HatModelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TargetQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToLeadId");

                    b.HasIndex("BatchNumber")
                        .IsUnique();

                    b.HasIndex("HatModelId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.BatchWorkshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedMetersPerUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("InitialMaterialQty")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaterialUsed")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("MaterialsReceived")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresMaterials")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.HasIndex("BatchId", "WorkshopId")
                        .IsUnique();

                    b.ToTable("BatchWorkshops");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.HatModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HatModels");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.LeadTaskDelegationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("AssignedTransportQcId")
                        .HasColumnType("integer");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompletedByTransportQcId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaterialDeliveryId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaterialRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RequestedByLeadId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedByAdminId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TransferRequestId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTransportQcId");

                    b.HasIndex("BatchId")
                        .IsUnique()
                        .HasDatabaseName("UX_LeadTaskDelegationRequests_ActiveFinalReview")
                        .HasFilter("\"Type\" = 2 AND \"Status\" IN (0, 1)");

                    b.HasIndex("CompletedByTransportQcId");

                    b.HasIndex("MaterialDeliveryId")
                        .IsUnique()
                        .HasDatabaseName("UX_LeadTaskDelegationRequests_ActiveMaterialDelivery")
                        .HasFilter("\"Type\" = 0 AND \"Status\" IN (0, 1) AND \"MaterialDeliveryId\" IS NOT NULL");

                    b.HasIndex("MaterialRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_LeadTaskDelegationRequests_ActiveMaterialRequestFulfillment")
                        .HasFilter("\"Type\" = 3 AND \"Status\" IN (0, 1, 3) AND \"MaterialRequestId\" IS NOT NULL");

                    b.HasIndex("RequestedByLeadId");

                    b.HasIndex("ReviewedByAdminId");

                    b.HasIndex("TransferRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_LeadTaskDelegationRequests_ActiveTransferApproval")
                        .HasFilter("\"Type\" = 1 AND \"Status\" IN (0, 1) AND \"TransferRequestId\" IS NOT NULL");

                    b.HasIndex("Type", "BatchId", "Status");

                    b.HasIndex("Type", "MaterialDeliveryId", "Status");

                    b.HasIndex("Type", "MaterialRequestId", "Status");

                    b.HasIndex("Type", "TransferRequestId", "Status");

                    b.ToTable("LeadTaskDelegationRequests", t =>
                        {
                            t.HasCheckConstraint("CK_LeadTaskDelegationRequests_ExactlyOneTask", "(\"Type\" = 0 AND \"MaterialDeliveryId\" IS NOT NULL AND \"TransferRequestId\" IS NULL AND \"MaterialRequestId\" IS NULL)\n                      OR (\"Type\" = 1 AND \"TransferRequestId\" IS NOT NULL AND \"MaterialDeliveryId\" IS NULL AND \"MaterialRequestId\" IS NULL)\n                      OR (\"Type\" = 2 AND \"MaterialDeliveryId\" IS NULL AND \"TransferRequestId\" IS NULL AND \"MaterialRequestId\" IS NULL)\n                      OR (\"Type\" = 3 AND \"MaterialRequestId\" IS NOT NULL AND \"MaterialDeliveryId\" IS NULL AND \"TransferRequestId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("HatForge.Domain.Entities.MaterialDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ConfirmedByQCId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("MaterialDeliveries");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.MaterialDeliveryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialDeliveryId")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialDeliveryId");

                    b.ToTable("MaterialDeliveryItems");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.MaterialRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedByLeadId")
                        .HasColumnType("integer");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByQCId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeliveredByTransportQcId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FulfilledByQCId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdHoc")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaterialDeliveryId")
                        .HasColumnType("integer");

                    b.Property<int?>("OriginalDeliveryId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByLeadId");

                    b.HasIndex("BatchId");

                    b.HasIndex("CreatedByQCId");

                    b.HasIndex("DeliveredByTransportQcId");

                    b.HasIndex("FulfilledByQCId");

                    b.HasIndex("MaterialDeliveryId");

                    b.HasIndex("OriginalDeliveryId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("MaterialRequests");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.MaterialRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("MaterialRequestId")
                        .HasColumnType("integer");

                    b.Property<int>("ShortfallQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialRequestId");

                    b.ToTable("MaterialRequestItems");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.TransferRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedByLeadId")
                        .HasColumnType("integer");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ConfirmedByQCId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByQCId")
                        .HasColumnType("integer");

                    b.Property<int>("FromWorkshopId")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiptInspectionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ReceivedDefectiveQuantity")
                        .HasColumnType("integer");

                    b.Property<int?>("ReceivedUsableQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("ToWorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByLeadId");

                    b.HasIndex("BatchId");

                    b.HasIndex("ConfirmedByQCId");

                    b.HasIndex("CreatedByQCId");

                    b.HasIndex("FromWorkshopId");

                    b.HasIndex("ToWorkshopId");

                    b.ToTable("TransferRequests");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("WorkshopId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualMaterialUsed")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("EstimatedMaterialUsed")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<bool>("IsRework")
                        .HasColumnType("boolean");

                    b.Property<int>("PassedQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RepairableQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedByQCId")
                        .HasColumnType("integer");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UnrepairableQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ReviewedByQCId");

                    b.HasIndex("StaffId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.WorkPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.ToTable("WorkPhotos");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("RequiresMaterials")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.Batch", b =>
                {
                    b.HasOne("HatForge.Domain.Entities.User", "AssignedToLead")
                        .WithMany()
                        .HasForeignKey("AssignedToLeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HatForge.Domain.Entities.HatModel", "HatModel")
                        .WithMany("Batches")
                        .HasForeignKey("HatModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToLead");

                    b.Navigation("HatModel");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.BatchWorkshop", b =>
                {
                    b.HasOne("HatForge.Domain.Entities.Batch", "Batch")
                        .WithMany("BatchWorkshops")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HatForge.Domain.Entities.Workshop", "Workshop")
                        .WithMany("BatchWorkshops")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.LeadTaskDelegationRequest", b =>
                {
                    b.HasOne("HatForge.Domain.Entities.User", "AssignedTransportQc")
                        .WithMany()
                        .HasForeignKey("AssignedTransportQcId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HatForge.Domain.Entities.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HatForge.Domain.Entities.User", "CompletedByTransportQc")
                        .WithMany()
                        .HasForeignKey("CompletedByTransportQcId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HatForge.Domain.Entities.MaterialDelivery", "MaterialDelivery")
                        .WithMany()
                        .HasForeignKey("MaterialDeliveryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HatForge.Domain.Entities.MaterialRequest", "MaterialRequest")
                        .WithMany()
                        .HasForeignKey("MaterialRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HatForge.Domain.Entities.User", "RequestedByLead")
                        .WithMany()
                        .HasForeignKey("RequestedByLeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HatForge.Domain.Entities.User", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HatForge.Domain.Entities.TransferRequest", "TransferRequest")
                        .WithMany()
                        .HasForeignKey("TransferRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedTransportQc");

                    b.Navigation("Batch");

                    b.Navigation("CompletedByTransportQc");

                    b.Navigation("MaterialDelivery");

                    b.Navigation("MaterialRequest");

                    b.Navigation("RequestedByLead");

                    b.Navigation("ReviewedByAdmin");

                    b.Navigation("TransferRequest");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.MaterialDelivery", b =>
                {
                    b.HasOne("HatForge.Domain.Entities.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HatForge.Domain.Entities.Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.MaterialDeliveryItem", b =>
                {
                    b.HasOne("HatForge.Domain.Entities.MaterialDelivery", "MaterialDelivery")
                        .WithMany("Items")
                        .HasForeignKey("MaterialDeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialDelivery");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.MaterialRequest", b =>
                {
                    b.HasOne("HatForge.Domain.Entities.User", "ApprovedByLead")
                        .WithMany()
                        .HasForeignKey("ApprovedByLeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HatForge.Domain.Entities.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HatForge.Domain.Entities.User", "CreatedByQC")
                        .WithMany()
                        .HasForeignKey("CreatedByQCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HatForge.Domain.Entities.User", "DeliveredByTransportQc")
                        .WithMany()
                        .HasForeignKey("DeliveredByTransportQcId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HatForge.Domain.Entities.User", "FulfilledByQC")
                        .WithMany()
                        .HasForeignKey("FulfilledByQCId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HatForge.Domain.Entities.MaterialDelivery", null)
                        .WithMany("MaterialRequests")
                        .HasForeignKey("MaterialDeliveryId");

                    b.HasOne("HatForge.Domain.Entities.MaterialDelivery", "OriginalDelivery")
                        .WithMany()
                        .HasForeignKey("OriginalDeliveryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HatForge.Domain.Entities.Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByLead");

                    b.Navigation("Batch");

                    b.Navigation("CreatedByQC");

                    b.Navigation("DeliveredByTransportQc");

                    b.Navigation("FulfilledByQC");

                    b.Navigation("OriginalDelivery");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.MaterialRequestItem", b =>
                {
                    b.HasOne("HatForge.Domain.Entities.MaterialRequest", "MaterialRequest")
                        .WithMany("Items")
                        .HasForeignKey("MaterialRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialRequest");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.Notification", b =>
                {
                    b.HasOne("HatForge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.TransferRequest", b =>
                {
                    b.HasOne("HatForge.Domain.Entities.User", "ApprovedByLead")
                        .WithMany()
                        .HasForeignKey("ApprovedByLeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HatForge.Domain.Entities.Batch", "Batch")
                        .WithMany("TransferRequests")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HatForge.Domain.Entities.User", "ConfirmedByQC")
                        .WithMany()
                        .HasForeignKey("ConfirmedByQCId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HatForge.Domain.Entities.User", "CreatedByQC")
                        .WithMany()
                        .HasForeignKey("CreatedByQCId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HatForge.Domain.Entities.Workshop", "FromWorkshop")
                        .WithMany()
                        .HasForeignKey("FromWorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HatForge.Domain.Entities.Workshop", "ToWorkshop")
                        .WithMany()
                        .HasForeignKey("ToWorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByLead");

                    b.Navigation("Batch");

                    b.Navigation("ConfirmedByQC");

                    b.Navigation("CreatedByQC");

                    b.Navigation("FromWorkshop");

                    b.Navigation("ToWorkshop");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.User", b =>
                {
                    b.HasOne("HatForge.Domain.Entities.Workshop", "Workshop")
                        .WithMany("Users")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.Work", b =>
                {
                    b.HasOne("HatForge.Domain.Entities.Batch", "Batch")
                        .WithMany("Works")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HatForge.Domain.Entities.User", "ReviewedByQC")
                        .WithMany()
                        .HasForeignKey("ReviewedByQCId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HatForge.Domain.Entities.User", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HatForge.Domain.Entities.Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("ReviewedByQC");

                    b.Navigation("Staff");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.WorkPhoto", b =>
                {
                    b.HasOne("HatForge.Domain.Entities.Work", "Work")
                        .WithMany("Photos")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.Batch", b =>
                {
                    b.Navigation("BatchWorkshops");

                    b.Navigation("TransferRequests");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.HatModel", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.MaterialDelivery", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("MaterialRequests");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.MaterialRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.Work", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("HatForge.Domain.Entities.Workshop", b =>
                {
                    b.Navigation("BatchWorkshops");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
